### ISSUE TITLE
Button "Delete" on PaaS Manager GUI not working

### ISSUE THREAD

**Issue by bonigarcia** [nubomedia/bugtracker#1]
I am using the new version of the production PaaS manager and I found a minor issue. The red button "Delete" for deployed apps does not seem to work properly. Please see these snapshots for further information:
![screenshot from 2016-08-24 09 57 20](https://cloud.githubusercontent.com/assets/5413013/17926414/3ed25c68-69f1-11e6-9971-1233d49ff962.png)
![screenshot from 2016-08-24 09 57 27](https://cloud.githubusercontent.com/assets/5413013/17926398/2c4826ae-69f1-11e6-9f51-2c8f11e03e5e.png)

**Comment by gc4rella** [comment]
Just fixed it.

**Comment by bonigarcia** [comment]
The problem seems to be still there. Now the GUI says "`Applications: xxxx deleted.`", but the application is not deleted.

**Comment by gc4rella** [comment]
just to be sure, is it working if you try again the deletion? I just want to be sure that it is not the same problem reported before...

**Comment by bonigarcia** [comment]
I select an existing application with the checkbox, the I click on "Delete" on the top of the page, and the GUI returns the message "Applications: xxxx deleted", but the application is not deleted. It is not the same problem (it's not the 405 error), but in the end the button is not working.

**Comment by gc4rella** [comment]
Ok. we have noticed the same problem just in few cases, and the app goes in failed state afterwards. Can you confirm that you have the same issue? because we're already working on fixing this type of issue.

**Comment by bonigarcia** [comment]
No, the app remains in the same state (not deleted but running).
